repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Generate helm README.md
        entry: helm-docs
        language: system
        files: '(Chart.yaml|values.yaml|requirements.yaml|README\.md\.gotmpl)$'