repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Generate helm README.md
        entry: helm-docs
        language: system
        pass_filenames: false
        files: 'deploy-templates/(Chart.yaml|values.yaml|requirements.yaml|README\.md\.gotmpl)$'